### ISSUE TITLE
Questions on this tool

### ISSUE THREAD

**Issue by BradKML** [TC-Zheng/ActuosusAI#19]
1. Are there ways to automate this "guardrail" tool such that the first words with the strongest "heat" will be forced to pick the answer(s) that that not so service-y? Traversing through the top answers until there are X options that does not dodge the question?
2. If this can be done, then that means it can also be used to do pro-con analysis where the same model can take stances on either side of an argument and make divergent thinking easier. How can this be automated?

**Comment by TC-Zheng** [comment]
Hi, I am not too sure about your first question, maybe you can explain it more clearly. 

But for the second question, you can certain do pro-con analysis with any model by simply instruct them to do so. Like just asking chatGPT to analyze different stances on a problem directly and I think it will do just fine. This tool is mostly intended as an interactive tool for you to interact with the model word by word.

**Comment by BradKML** [comment]
For the first question, a lot of LLMs have guardrails that prevents them from giving a controversial answer, but if there are a way to auto-check each of the possible tokens that can guide it to "tell the truth" then it would be great, like the example given... except it picked the least likely in the dropdown instead of checking each word in the distribution

**Comment by TC-Zheng** [comment]
I guess it is possible to first train a small Sentiment analysis llm (like just bert or something) to detect any kind of "refusing answer" like "Sorry I cannot answer question regard X", then try to pick a new token somewhere whenever that happened. That could be an interesting idea to try.
